#!/bin/bash

sudo apt-get update -y

sudo apt-get install apache2 -y

sudo apt-get install mysql-server -y

sudo apt-get install php libapache2-mod-php php-mysql -y

sudo apt-get install git composer -y

cd /var/www/html
